### ISSUE TITLE
UI Size of Main and Confirmation page Bugs.

### ISSUE THREAD

**Issue by Joseph1818** [Joseph1818/NewsLetterWebApp#2]
The size of the UI main page display according to which size of screen you using, for instance if you displaying on a Laptop screen (fonts, and images) is normal. but if you displaying on a Monitor it fits small. The images and font property need to be reviewed
#Bugs that need to be fixed
![Screenshot 2023-07-27 at 17 25 21 (2)](https://github.com/Joseph1818/NewsLetterWebApp/assets/43114099/eecce883-2d9f-4a6a-8045-807978b69c65)
<img width="1440" alt="Screenshot 2023-07-27 at 17 25 45" src="https://github.com/Joseph1818/NewsLetterWebApp/assets/43114099/f79409ed-72b1-4310-b055-765a34ae064a">
<img width="1440" alt="Screenshot 2023-07-27 at 18 08 30" src="https://github.com/Joseph1818/NewsLetterWebApp/assets/43114099/cfc3f69f-2032-4a8b-8339-06f6bedf4e20">

**Comment by Chadrackmbuyi01** [comment]
The task assigned has been completed
